# =============================== 核心配置 ================================
# ----------------- bot -------------------
bots:
  core:
    loginInfo: # 机器人的账号密码
      - 123456:654321a
      - 654321:123456z

# ----------------- sizhi -----------------
sizhi:
  appId: "appid"

# --------------- spring ---------------
server:
  port: 8081

spring:
  profiles: dev

  # ================================= 连接配置 ==================================
  # ---------------- redis ----------------
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000 # 超时时间，毫秒

  # ----------------- mysql ------------------
  datasource:
    driver-class-name:
    username:
    password:
    url:
    filters: stat,wall,log4j

# ---------------- mybatis ----------------
mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
